### ISSUE TITLE
bootstrap-import.css should contain only styles for boostrap custom elements

### ISSUE THREAD

**Issue by medikoo** [egovernment/eregistrations#12]
e.g. below is completely generic, it's not about custom bootstrap elements

``` css
input,
button,
select,
textarea {
font-family: inherit;
font-size: inherit;
line-height: inherit;
}
a {
color: #428bca;
text-decoration: none;
}
a:hover,
a:focus {
color: #2a6496;
text-decoration: underline;
}
a:focus {
outline: thin dotted;
outline: 5px auto -webkit-focus-ring-color;
outline-offset: -2px;
}
figure {
margin: 0;
}
``
```
